defaults:
  - scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "_projects"
      collection: "projects"
    values:
      layout: "project"

collections:
  projects:
    output: true

plugins:
  - jekyll-feed
  - jekyll-sitemap