defaults:
  - scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "_projects"
      collection: "projects"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

author:
  name: "andy chan"
  twitter: "12bz_trenchcoat"

collections:
  projects:
    output: true

feed:
  collections:
    - projects

highlighter: rouge

timezone: America/New_York

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    span: 
      line_numbers: false
    block: 
      line_numbers: true

sass:
  style: compressed
  sourcemap: development
  implementation: sass-embedded

url: "https://12beesinatrenchcoat.github.io"

plugins:
  - jekyll-feed
  - jekyll-sitemap
